# Generated by Django 4.1.5 on 2023-07-06 11:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bingosync', '0038_player_is_referee'),
    ]

    operations = [
        migrations.CreateModel(
            name='KickPlayerEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sent')),
                ('player_color_value', models.IntegerField(choices=[(2, 'Red'), (3, 'Blue'), (4, 'Green'), (5, 'Orange'), (6, 'Purple'), (7, 'Navy'), (8, 'Teal'), (9, 'Pink'), (10, 'Brown'), (11, 'Yellow')])),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bingosync.player')),
                ('player_to_kick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_to_kick', to='bingosync.player')),
            ],
            options={
                'get_latest_by': 'timestamp',
                'abstract': False,
            },
        ),
    ]
