# Generated by Django 4.1.5 on 2023-07-06 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bingosync', '0039_kickplayerevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kickplayerevent',
            name='player_to_kick',
        ),
    ]
